const Router = require('express')
const router = new Router()
const itemController = require('../controllers/itemController')

router.post('/', itemController.create)
router.post('/createall', itemController.createAll)
router.post('/createxl', itemController.createXL)
router.post('/update', itemController.update)
router.post('/buy', itemController.buyItems)
router.get('/one/:id', itemController.getOne)
router.get('/same', itemController.getSame)
router.get('/originals', itemController.getOriginals)
router.get('/replicas', itemController.getReplicas)
router.get('/restored', itemController.getRestored)
router.get('/all', itemController.getAll)
router.get('/combs', itemController.getCombs)
router.get('/count', itemController.getCount)
router.get('/brands', itemController.getBrands)
router.get('/grips', itemController.getGrips)
router.get('/bends', itemController.getBends)
router.get('/rigidities', itemController.getRigidities)
router.get('/min', itemController.getMin)
router.get('/max', itemController.getMax)
router.delete('/', itemController.delete)
router.delete('/many', itemController.deleteMany)

module.exports = router